export const ELECTRICAL_COMPONENTS = [
  // ── Original 10 ────────────────────────────────────────────────────────────
  {
    type: 'resistor',
    label: 'Resistor',
    tags: ['passive', 'R', 'resistance'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'R',
    defaultValue: '1kΩ',
    width: 40,
    height: 20,
    viewBox: '-22 -12 44 24',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      resistance: { label: 'Resistance (Ω)', type: 'number', default: 1000, primary: true, unit: 'Ω' },
      powerRating: { label: 'Power Rating (W)', type: 'number', default: 0.25 },
    },
  },
  {
    type: 'capacitor',
    label: 'Capacitor',
    tags: ['passive', 'C', 'capacitance'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'C',
    defaultValue: '100nF',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      capacitance: { label: 'Capacitance (F)', type: 'number', default: 1e-7, primary: true, unit: 'F' },
      voltageRating: { label: 'Voltage Rating (V)', type: 'number', default: 50 },
    },
  },
  {
    type: 'switch_no',
    label: 'Switch (NO)',
    tags: ['switch', 'SPST', 'normally open', 'S'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'S',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -16 44 22',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    // Normally-open: fixed open at rest (see getSymbolState in PlacedComponent).
    // Toggled only by clicking during simulation; no configurable initial state.
  },
  {
    type: 'pushbutton_no',
    label: 'Push Button (NO)',
    tags: ['button', 'push', 'momentary', 'PB'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PB',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -22 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'led',
    label: 'LED',
    tags: ['LED', 'diode', 'light', 'indicator', 'D'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'LED',
    defaultValue: 'Red',
    width: 40,
    height: 24,
    viewBox: '-22 -18 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'K', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      forwardVoltage: { label: 'Forward Voltage (V)', type: 'number', default: 2.1 },
      forwardCurrent: { label: 'Forward Current (mA)', type: 'number', default: 20 },
    },
  },
  {
    type: 'battery',
    label: 'Battery',
    tags: ['battery', 'voltage source', 'DC', 'BT', 'power'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'BT',
    defaultValue: '12V',
    width: 40,
    height: 30,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'NEG', relX: -20, relY: 0, direction: 'W' },
      { id: 'POS', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Voltage (V)', type: 'number', default: 12, primary: true, unit: 'V' },
      internalResistance: { label: 'Internal Resistance (Ω)', type: 'number', default: 0.1 },
    },
  },
  {
    type: 'ground',
    label: 'Ground',
    tags: ['ground', 'GND', 'earth', 'common'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'GND',
    defaultValue: '',
    width: 30,
    height: 22,
    viewBox: '-16 -2 32 26',
    pins: [
      { id: 'GND', relX: 0, relY: 0, direction: 'N' },
    ],
    simParams: {},
  },
  {
    type: 'relay_coil',
    label: 'Relay Coil',
    tags: ['relay', 'coil', 'K', 'contactor'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'K',
    defaultValue: '24VDC',
    width: 40,
    height: 20,
    viewBox: '-22 -12 44 24',
    pins: [
      { id: 'A1', relX: -20, relY: 0, direction: 'W' },
      { id: 'A2', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      coilVoltage: { label: 'Coil Voltage (V)', type: 'number', default: 24 },
      pickupVoltage: { label: 'Pickup Voltage (V)', type: 'number', default: 18 },
    },
  },
  {
    type: 'relay_contact_no',
    label: 'Relay Contact (NO)',
    tags: ['relay', 'contact', 'NO', 'normally open', 'K'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'K',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -22 44 26',
    pins: [
      { id: 'C', relX: -20, relY: 0, direction: 'W' },
      { id: 'NO', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'lamp',
    label: 'Lamp',
    tags: ['lamp', 'light', 'bulb', 'indicator', 'HL'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'HL',
    defaultValue: '24V',
    width: 40,
    height: 24,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Rated Voltage (V)', type: 'number', default: 24 },
      power: { label: 'Power (W)', type: 'number', default: 5 },
    },
  },

  // ── Power & Sources ─────────────────────────────────────────────────────────
  {
    type: 'dc_current_source',
    label: 'DC Current Source',
    tags: ['current source', 'DC', 'I', 'source'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'I',
    defaultValue: '1A',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'NEG', relX: -20, relY: 0, direction: 'W' },
      { id: 'POS', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      current: { label: 'Current (A)', type: 'number', default: 1, primary: true, unit: 'A' },
    },
  },
  {
    type: 'ac_voltage_source',
    label: 'AC Voltage Source',
    tags: ['AC', 'voltage source', 'sine', 'mains', 'V'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'V',
    defaultValue: '230VAC',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Voltage RMS (V)', type: 'number', default: 230, primary: true, unit: 'V' },
      frequency: { label: 'Frequency (Hz)', type: 'number', default: 50 },
    },
  },
  {
    type: 'vcc_rail',
    label: 'VCC Rail',
    tags: ['VCC', 'VDD', 'power rail', 'supply', '+V'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'VCC',
    defaultValue: '+5V',
    width: 30,
    height: 22,
    viewBox: '-16 -24 32 26',
    pins: [
      { id: 'PWR', relX: 0, relY: 0, direction: 'S' },
    ],
    simParams: {
      voltage: { label: 'Voltage (V)', type: 'number', default: 5, primary: true, unit: 'V' },
    },
  },
  {
    type: 'vss_rail',
    label: 'VSS Rail',
    tags: ['VSS', 'GND', 'power rail', 'negative', '-V'],
    category: 'Power & Sources',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'VSS',
    defaultValue: '0V',
    width: 30,
    height: 22,
    viewBox: '-16 -2 32 26',
    pins: [
      { id: 'GND', relX: 0, relY: 0, direction: 'N' },
    ],
    simParams: {},
  },

  // ── Passive Components ──────────────────────────────────────────────────────
  {
    type: 'variable_resistor',
    label: 'Variable Resistor',
    tags: ['variable resistor', 'rheostat', 'VR', 'adjustable'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'VR',
    defaultValue: '10kΩ',
    width: 40,
    height: 20,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      resistance: { label: 'Resistance (Ω)', type: 'number', default: 10000, primary: true, unit: 'Ω' },
      position: { label: 'Wiper Position (0–1)', type: 'number', default: 0.5 },
    },
  },
  {
    type: 'potentiometer',
    label: 'Potentiometer',
    tags: ['potentiometer', 'pot', 'RV', 'variable', 'wiper'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'RV',
    defaultValue: '10kΩ',
    width: 40,
    height: 30,
    viewBox: '-22 -12 44 34',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
      { id: 'W', relX: 0, relY: 20, direction: 'S' },
    ],
    simParams: {
      resistance: { label: 'Total Resistance (Ω)', type: 'number', default: 10000, primary: true, unit: 'Ω' },
      position: { label: 'Wiper Position (0–1)', type: 'number', default: 0.5 },
    },
  },
  {
    type: 'electrolytic_capacitor',
    label: 'Electrolytic Cap',
    tags: ['electrolytic', 'capacitor', 'polarised', 'CE', 'C'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'C',
    defaultValue: '100µF',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 32',
    pins: [
      { id: 'POS', relX: -20, relY: 0, direction: 'W' },
      { id: 'NEG', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      capacitance: { label: 'Capacitance (F)', type: 'number', default: 1e-4, primary: true, unit: 'F' },
      voltageRating: { label: 'Voltage Rating (V)', type: 'number', default: 25 },
    },
  },
  {
    type: 'inductor',
    label: 'Inductor',
    tags: ['inductor', 'coil', 'L', 'choke'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'L',
    defaultValue: '10mH',
    width: 40,
    height: 16,
    viewBox: '-22 -10 44 20',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      inductance: { label: 'Inductance (H)', type: 'number', default: 0.01, primary: true, unit: 'H' },
      dcr: { label: 'DC Resistance (Ω)', type: 'number', default: 0.1 },
    },
  },
  {
    type: 'transformer',
    label: 'Transformer',
    tags: ['transformer', 'T', 'coupled', 'isolation'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'T',
    defaultValue: '1:1',
    width: 44,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'P1', relX: -20, relY: -10, direction: 'W' },
      { id: 'P2', relX: -20, relY: 10, direction: 'W' },
      { id: 'S1', relX: 20, relY: -10, direction: 'E' },
      { id: 'S2', relX: 20, relY: 10, direction: 'E' },
    ],
    simParams: {
      turnsRatio: { label: 'Turns Ratio (N:1)', type: 'number', default: 1 },
    },
  },
  {
    type: 'diode',
    label: 'Diode',
    tags: ['diode', 'D', 'rectifier', 'semiconductor'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'D',
    defaultValue: '1N4007',
    width: 40,
    height: 24,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'K', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      forwardVoltage: { label: 'Forward Voltage (V)', type: 'number', default: 0.7 },
      reverseVoltage: { label: 'Reverse Voltage (V)', type: 'number', default: 1000 },
    },
  },
  {
    type: 'zener_diode',
    label: 'Zener Diode',
    tags: ['zener', 'diode', 'DZ', 'regulator', 'breakdown'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'DZ',
    defaultValue: '5.1V',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'K', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      zenerVoltage: { label: 'Zener Voltage (V)', type: 'number', default: 5.1, primary: true, unit: 'V' },
    },
  },
  {
    type: 'photodiode',
    label: 'Photodiode',
    tags: ['photodiode', 'PD', 'light sensor', 'optical'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PD',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -20 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'K', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      sensitivity: { label: 'Sensitivity (A/W)', type: 'number', default: 0.5 },
    },
  },
  {
    type: 'fuse',
    label: 'Fuse',
    tags: ['fuse', 'F', 'protection', 'overcurrent'],
    category: 'Passive',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'F',
    defaultValue: '1A',
    width: 40,
    height: 20,
    viewBox: '-22 -12 44 24',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      currentRating: { label: 'Current Rating (A)', type: 'number', default: 1, primary: true, unit: 'A' },
      voltageRating: { label: 'Voltage Rating (V)', type: 'number', default: 250 },
    },
  },

  // ── Switches & Controls ─────────────────────────────────────────────────────
  {
    type: 'switch_nc',
    label: 'Switch (NC)',
    tags: ['switch', 'SPST', 'normally closed', 'NC', 'S'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'S',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -18 44 22',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    // Normally-closed: fixed closed at rest (see getSymbolState in PlacedComponent).
    // Toggled only by clicking during simulation; no configurable initial state.
  },
  {
    type: 'switch_spdt',
    label: 'Switch (SPDT)',
    tags: ['switch', 'SPDT', 'single pole double throw', 'S'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'S',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'COM', relX: -20, relY: 0, direction: 'W' },
      { id: 'NO', relX: 20, relY: -10, direction: 'E' },
      { id: 'NC', relX: 20, relY: 10, direction: 'E' },
    ],
    simParams: {
      position: { label: 'Position', type: 'select', options: ['NO', 'NC'], default: 'NO' },
    },
  },
  {
    type: 'pushbutton_nc',
    label: 'Push Button (NC)',
    tags: ['button', 'push', 'momentary', 'NC', 'normally closed', 'PB'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PB',
    defaultValue: '',
    width: 40,
    height: 24,
    viewBox: '-22 -18 44 24',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'limit_switch',
    label: 'Limit Switch',
    tags: ['limit switch', 'LS', 'position', 'actuator'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'LS',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -26 44 30',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    // Open at rest (see getSymbolState); toggled only by clicking during simulation.
  },
  {
    type: 'proximity_switch',
    label: 'Proximity Switch',
    tags: ['proximity', 'sensor', 'PX', 'inductive', 'capacitive'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PX',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -26 44 30',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    // Open at rest (see getSymbolState); toggled only by clicking during simulation.
  },
  {
    type: 'pressure_switch',
    label: 'Pressure Switch',
    tags: ['pressure switch', 'PS', 'pressure', 'sensor'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PS',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -26 44 30',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      setPoint: { label: 'Set Point (bar)', type: 'number', default: 5 },
    },
  },
  {
    type: 'temperature_switch',
    label: 'Temperature Switch',
    tags: ['thermostat', 'temperature switch', 'TS', 'thermal'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'TS',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -26 44 30',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      setPoint: { label: 'Set Point (°C)', type: 'number', default: 80 },
    },
  },

  // ── Logic Gates ─────────────────────────────────────────────────────────────
  {
    type: 'gate_and',
    label: 'AND Gate',
    tags: ['AND', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_or',
    label: 'OR Gate',
    tags: ['OR', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_not',
    label: 'NOT Gate',
    tags: ['NOT', 'inverter', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_nand',
    label: 'NAND Gate',
    tags: ['NAND', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_nor',
    label: 'NOR Gate',
    tags: ['NOR', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_xor',
    label: 'XOR Gate',
    tags: ['XOR', 'exclusive or', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_xnor',
    label: 'XNOR Gate',
    tags: ['XNOR', 'exclusive nor', 'logic', 'gate', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: -8, direction: 'W' },
      { id: 'B', relX: -20, relY: 8, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'gate_buffer',
    label: 'Buffer',
    tags: ['buffer', 'logic', 'gate', 'digital', 'driver'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'schmitt_trigger',
    label: 'Schmitt Trigger',
    tags: ['schmitt', 'trigger', 'hysteresis', 'logic', 'digital'],
    category: 'Logic',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'Y', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },

  // ── Semiconductors & Active ─────────────────────────────────────────────────
  {
    type: 'npn_transistor',
    label: 'NPN Transistor',
    tags: ['NPN', 'BJT', 'transistor', 'Q', 'amplifier'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'Q',
    defaultValue: 'BC547',
    width: 40,
    height: 44,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'B', relX: -20, relY: 0, direction: 'W' },
      { id: 'C', relX: 10, relY: -20, direction: 'N' },
      { id: 'E', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      hFE: { label: 'DC Gain (hFE)', type: 'number', default: 100 },
      vCEsat: { label: 'Vce Sat (V)', type: 'number', default: 0.2 },
    },
  },
  {
    type: 'pnp_transistor',
    label: 'PNP Transistor',
    tags: ['PNP', 'BJT', 'transistor', 'Q', 'amplifier'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'Q',
    defaultValue: 'BC557',
    width: 40,
    height: 44,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'B', relX: -20, relY: 0, direction: 'W' },
      { id: 'C', relX: 10, relY: -20, direction: 'N' },
      { id: 'E', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      hFE: { label: 'DC Gain (hFE)', type: 'number', default: 100 },
      vCEsat: { label: 'Vce Sat (V)', type: 'number', default: 0.2 },
    },
  },
  {
    type: 'nmos_transistor',
    label: 'N-MOSFET',
    tags: ['NMOS', 'MOSFET', 'FET', 'transistor', 'Q'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'Q',
    defaultValue: '2N7000',
    width: 40,
    height: 44,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'G', relX: -20, relY: -10, direction: 'W' },
      { id: 'D', relX: 10, relY: -20, direction: 'N' },
      { id: 'S', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      vth: { label: 'Threshold Vgs (V)', type: 'number', default: 2 },
      rdson: { label: 'Rds(on) (Ω)', type: 'number', default: 0.1 },
    },
  },
  {
    type: 'pmos_transistor',
    label: 'P-MOSFET',
    tags: ['PMOS', 'MOSFET', 'FET', 'transistor', 'Q'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'Q',
    defaultValue: 'IRF9540',
    width: 40,
    height: 44,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'G', relX: -20, relY: -10, direction: 'W' },
      { id: 'D', relX: 10, relY: -20, direction: 'N' },
      { id: 'S', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      vth: { label: 'Threshold |Vgs| (V)', type: 'number', default: 2 },
      rdson: { label: 'Rds(on) (Ω)', type: 'number', default: 0.1 },
    },
  },
  {
    type: 'njfet_transistor',
    label: 'N-JFET',
    tags: ['NJFET', 'JFET', 'FET', 'transistor', 'J'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'J',
    defaultValue: '2N5457',
    width: 40,
    height: 44,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'G', relX: -20, relY: -10, direction: 'W' },
      { id: 'D', relX: 10, relY: -20, direction: 'N' },
      { id: 'S', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      idss: { label: 'Idss (mA)', type: 'number', default: 5 },
      vp: { label: 'Pinch-off Vp (V)', type: 'number', default: -2 },
    },
  },
  {
    type: 'scr',
    label: 'SCR / Thyristor',
    tags: ['SCR', 'thyristor', 'silicon controlled rectifier', 'TH'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'TH',
    defaultValue: 'MCR100',
    width: 40,
    height: 30,
    viewBox: '-22 -14 44 34',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'K', relX: 20, relY: 0, direction: 'E' },
      { id: 'G', relX: 10, relY: 20, direction: 'S' },
    ],
    simParams: {
      holdingCurrent: { label: 'Holding Current (mA)', type: 'number', default: 5 },
    },
  },
  {
    type: 'triac',
    label: 'TRIAC',
    tags: ['TRIAC', 'bidirectional', 'thyristor', 'AC switch'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'TH',
    defaultValue: 'BT136',
    width: 40,
    height: 30,
    viewBox: '-22 -14 44 34',
    pins: [
      { id: 'T1', relX: -20, relY: 0, direction: 'W' },
      { id: 'T2', relX: 20, relY: 0, direction: 'E' },
      { id: 'G', relX: 0, relY: 20, direction: 'S' },
    ],
    simParams: {
      holdingCurrent: { label: 'Holding Current (mA)', type: 'number', default: 10 },
    },
  },
  {
    type: 'op_amp',
    label: 'Op-Amp',
    tags: ['op-amp', 'operational amplifier', 'U', 'amplifier'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: 'LM741',
    width: 44,
    height: 36,
    viewBox: '-22 -20 44 40',
    pins: [
      { id: 'IN-', relX: -20, relY: -8, direction: 'W' },
      { id: 'IN+', relX: -20, relY: 8, direction: 'W' },
      { id: 'OUT', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      gain: { label: 'Open-Loop Gain (dB)', type: 'number', default: 120 },
      bandwidth: { label: 'Bandwidth (MHz)', type: 'number', default: 1 },
    },
  },
  {
    type: 'comparator',
    label: 'Comparator',
    tags: ['comparator', 'COMP', 'U', 'voltage compare'],
    category: 'Semiconductors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'U',
    defaultValue: 'LM393',
    width: 44,
    height: 36,
    viewBox: '-22 -20 44 40',
    pins: [
      { id: 'IN-', relX: -20, relY: -8, direction: 'W' },
      { id: 'IN+', relX: -20, relY: 8, direction: 'W' },
      { id: 'OUT', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      hysteresis: { label: 'Hysteresis (mV)', type: 'number', default: 0 },
    },
  },

  // ── Electromechanical ───────────────────────────────────────────────────────
  {
    type: 'relay_contact_nc',
    label: 'Relay Contact (NC)',
    tags: ['relay', 'contact', 'NC', 'normally closed', 'K'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'K',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -22 44 26',
    pins: [
      { id: 'C', relX: -20, relY: 0, direction: 'W' },
      { id: 'NC', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'relay_contact_spdt',
    label: 'Relay Contact (SPDT)',
    tags: ['relay', 'contact', 'SPDT', 'changeover', 'K'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'K',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -24 44 36',
    pins: [
      { id: 'C', relX: -20, relY: 0, direction: 'W' },
      { id: 'NO', relX: 20, relY: -10, direction: 'E' },
      { id: 'NC', relX: 20, relY: 10, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'solenoid',
    label: 'Solenoid',
    tags: ['solenoid', 'YV', 'coil', 'actuator'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'YV',
    defaultValue: '24VDC',
    width: 40,
    height: 20,
    viewBox: '-22 -14 44 24',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      coilVoltage: { label: 'Coil Voltage (V)', type: 'number', default: 24 },
      coilResistance: { label: 'Coil Resistance (Ω)', type: 'number', default: 20 },
    },
  },
  {
    type: 'motor',
    label: 'Motor',
    tags: ['motor', 'M', 'electric motor', 'DC motor'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'M',
    defaultValue: '24VDC',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Rated Voltage (V)', type: 'number', default: 24 },
      power: { label: 'Power (W)', type: 'number', default: 100 },
      rpm: { label: 'Rated Speed (RPM)', type: 'number', default: 1500 },
    },
  },
  {
    type: 'generator',
    label: 'Generator',
    tags: ['generator', 'G', 'alternator', 'dynamo'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'G',
    defaultValue: '230VAC',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Output Voltage (V)', type: 'number', default: 230 },
      frequency: { label: 'Frequency (Hz)', type: 'number', default: 50 },
    },
  },
  {
    type: 'contactor_coil',
    label: 'Contactor Coil',
    tags: ['contactor', 'coil', 'KM', 'power contactor'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'KM',
    defaultValue: '230VAC',
    width: 40,
    height: 20,
    viewBox: '-22 -12 44 24',
    pins: [
      { id: 'A1', relX: -20, relY: 0, direction: 'W' },
      { id: 'A2', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      coilVoltage: { label: 'Coil Voltage (V)', type: 'number', default: 230 },
    },
  },
  {
    type: 'contactor_no',
    label: 'Contactor Contact (NO)',
    tags: ['contactor', 'contact', 'NO', 'power', 'KM'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'KM',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -24 44 28',
    pins: [
      { id: 'C', relX: -20, relY: 0, direction: 'W' },
      { id: 'NO', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'contactor_nc',
    label: 'Contactor Contact (NC)',
    tags: ['contactor', 'contact', 'NC', 'power', 'KM'],
    category: 'Electromechanical',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'KM',
    defaultValue: '',
    width: 40,
    height: 20,
    viewBox: '-22 -22 44 26',
    pins: [
      { id: 'C', relX: -20, relY: 0, direction: 'W' },
      { id: 'NC', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },

  // ── Outputs / Indicators ────────────────────────────────────────────────────
  {
    type: 'buzzer',
    label: 'Buzzer',
    tags: ['buzzer', 'BZ', 'alarm', 'audio', 'piezo'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'BZ',
    defaultValue: '12V',
    width: 40,
    height: 24,
    viewBox: '-22 -14 44 28',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Rated Voltage (V)', type: 'number', default: 12 },
      frequency: { label: 'Frequency (Hz)', type: 'number', default: 2400 },
    },
  },
  {
    type: 'speaker',
    label: 'Speaker',
    tags: ['speaker', 'SP', 'audio', 'loudspeaker'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'SP',
    defaultValue: '8Ω',
    width: 44,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      impedance: { label: 'Impedance (Ω)', type: 'number', default: 8 },
      power: { label: 'Power (W)', type: 'number', default: 10 },
    },
  },
  {
    type: 'circuit_breaker',
    label: 'Circuit Breaker',
    tags: ['circuit breaker', 'CB', 'breaker', 'protection', 'QF'],
    category: 'Switches',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'QF',
    defaultValue: '10A',
    width: 40,
    height: 28,
    viewBox: '-22 -22 44 26',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      currentRating: { label: 'Current Rating (A)', type: 'number', default: 10 },
      breakingCapacity: { label: 'Breaking Capacity (kA)', type: 'number', default: 6 },
    },
  },
  {
    type: 'voltmeter',
    label: 'Voltmeter',
    tags: ['voltmeter', 'PV', 'meter', 'measurement', 'voltage'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PV',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'ammeter',
    label: 'Ammeter',
    tags: ['ammeter', 'PA', 'meter', 'measurement', 'current'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PA',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'wattmeter',
    label: 'Wattmeter',
    tags: ['wattmeter', 'PW', 'meter', 'measurement', 'power'],
    category: 'Outputs',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PW',
    defaultValue: '',
    width: 40,
    height: 28,
    viewBox: '-22 -16 44 32',
    pins: [
      { id: 'A', relX: -20, relY: 0, direction: 'W' },
      { id: 'B', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },

  // ── PLC I/O ─────────────────────────────────────────────────────────────────
  {
    type: 'plc_digital_output',
    label: 'PLC Digital Output',
    tags: ['PLC', 'digital output', 'DO', 'discrete', 'Q', 'output'],
    category: 'PLC I/O',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'DO',
    defaultValue: 'Q0.0',
    width: 44,
    height: 36,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'OUT', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Output Voltage (V)', type: 'number', default: 24 },
      maxCurrent: { label: 'Max Current (A)', type: 'number', default: 0.5 },
    },
  },
  {
    type: 'plc_pwm_output',
    label: 'PLC PWM Output',
    tags: ['PLC', 'PWM', 'pulse width modulation', 'output', 'Q'],
    category: 'PLC I/O',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'PWM',
    defaultValue: 'Q0.0',
    width: 44,
    height: 36,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'OUT', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      voltage: { label: 'Output Voltage (V)', type: 'number', default: 24 },
      frequency: { label: 'Frequency (Hz)', type: 'number', default: 1000 },
      dutyCycle: { label: 'Duty Cycle (%)', type: 'number', default: 50 },
    },
  },
  {
    type: 'plc_digital_input',
    label: 'PLC Digital Input',
    tags: ['PLC', 'digital input', 'DI', 'discrete', 'I', 'input'],
    category: 'PLC I/O',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'DI',
    defaultValue: 'I0.0',
    width: 44,
    height: 36,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'IN', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      threshold: { label: 'Switching Threshold (V)', type: 'number', default: 11 },
    },
  },
  {
    type: 'plc_analog_input',
    label: 'PLC Analogue Input',
    tags: ['PLC', 'analogue input', 'analog input', 'AI', 'IW', 'input'],
    category: 'PLC I/O',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'AI',
    defaultValue: 'IW64',
    width: 44,
    height: 36,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'IN', relX: 20, relY: 0, direction: 'E' },
    ],
    simParams: {
      range: {
        label: 'Signal Range',
        type: 'select',
        options: ['0–10 V', '0–20 mA', '4–20 mA', '±10 V'],
        default: '0–10 V',
      },
      resolution: { label: 'Resolution (bits)', type: 'number', default: 12 },
    },
  },

  // ── Connectors ──────────────────────────────────────────────────────────────
  // Interface/terminal symbols: housing outline + numbered cavities + on-line
  // leads. No DC-solver model — the solver no-ops unknown types.
  {
    type: 'conn_dt_2',
    label: 'Deutsch DT 2-Way',
    tags: ['connector', 'Deutsch', 'DT', '2-way', '2 pin', 'plug', 'header'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'X',
    defaultValue: 'DT04-2P',
    width: 40,
    height: 40,
    viewBox: '-20 -20 40 40',
    pins: [
      { id: '1', relX: 20, relY: -10, direction: 'E' },
      { id: '2', relX: 20, relY: 10, direction: 'E' },
    ],
  },
  {
    type: 'conn_dt_3',
    label: 'Deutsch DT 3-Way',
    tags: ['connector', 'Deutsch', 'DT', '3-way', '3 pin', 'plug', 'header'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'X',
    defaultValue: 'DT04-3P',
    width: 40,
    height: 60,
    viewBox: '-20 -30 40 60',
    pins: [
      { id: '1', relX: 20, relY: -20, direction: 'E' },
      { id: '2', relX: 20, relY: 0, direction: 'E' },
      { id: '3', relX: 20, relY: 20, direction: 'E' },
    ],
  },
  {
    type: 'conn_dt_4',
    label: 'Deutsch DT 4-Way',
    tags: ['connector', 'Deutsch', 'DT', '4-way', '4 pin', 'plug', 'header'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'X',
    defaultValue: 'DT04-4P',
    width: 40,
    height: 70,
    viewBox: '-20 -35 40 70',
    pins: [
      { id: '1', relX: 20, relY: -30, direction: 'E' },
      { id: '2', relX: 20, relY: -10, direction: 'E' },
      { id: '3', relX: 20, relY: 10, direction: 'E' },
      { id: '4', relX: 20, relY: 30, direction: 'E' },
    ],
  },
  {
    type: 'conn_acode_3',
    label: 'M12 A-Code 3-Pin',
    tags: ['connector', 'A-code', 'A-coded', 'M12', '3-pin', 'circular', 'sensor'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'X',
    defaultValue: 'M12-A 3P',
    width: 40,
    height: 60,
    viewBox: '-20 -30 40 60',
    pins: [
      { id: '1', relX: 20, relY: -20, direction: 'E' },
      { id: '2', relX: 20, relY: 0, direction: 'E' },
      { id: '3', relX: 20, relY: 20, direction: 'E' },
    ],
  },
  {
    type: 'conn_acode_4',
    label: 'M12 A-Code 4-Pin',
    tags: ['connector', 'A-code', 'A-coded', 'M12', '4-pin', 'circular', 'sensor'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'X',
    defaultValue: 'M12-A 4P',
    width: 40,
    height: 70,
    viewBox: '-20 -35 40 70',
    pins: [
      { id: '1', relX: 20, relY: -30, direction: 'E' },
      { id: '2', relX: 20, relY: -10, direction: 'E' },
      { id: '3', relX: 20, relY: 10, direction: 'E' },
      { id: '4', relX: 20, relY: 30, direction: 'E' },
    ],
  },
  {
    type: 'conn_header_2',
    label: 'Header 2-Way',
    tags: ['connector', 'header', 'generic', '2-way', '2 pin', 'terminal', 'pin header'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'J',
    defaultValue: '1x2',
    width: 40,
    height: 40,
    viewBox: '-20 -20 40 40',
    pins: [
      { id: '1', relX: 20, relY: -10, direction: 'E' },
      { id: '2', relX: 20, relY: 10, direction: 'E' },
    ],
  },
  {
    type: 'conn_header_4',
    label: 'Header 4-Way',
    tags: ['connector', 'header', 'generic', '4-way', '4 pin', 'terminal', 'pin header'],
    category: 'Connectors',
    schematicType: 'electrical',
    defaultDesignatorPrefix: 'J',
    defaultValue: '1x4',
    width: 40,
    height: 70,
    viewBox: '-20 -35 40 70',
    pins: [
      { id: '1', relX: 20, relY: -30, direction: 'E' },
      { id: '2', relX: 20, relY: -10, direction: 'E' },
      { id: '3', relX: 20, relY: 10, direction: 'E' },
      { id: '4', relX: 20, relY: 30, direction: 'E' },
    ],
  },
]

export const ALL_ELECTRICAL_TYPES = new Set(ELECTRICAL_COMPONENTS.map(c => c.type))

export function getElectricalDef(type) {
  return ELECTRICAL_COMPONENTS.find(c => c.type === type) || null
}
