// ISO 1219 hydraulic component definitions

export const HYDRAULIC_COMPONENTS = [
  // ── Power & Sources ─────────────────────────────────────────────────────────
  {
    type: 'hyd_pump_fixed',
    label: 'Fixed Pump',
    tags: ['pump', 'fixed', 'displacement', 'power', 'source', 'P'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'P',
    defaultValue: '',
    width: 40,
    height: 40,
    viewBox: '-24 -24 48 48',
    pins: [
      { id: 'IN',  relX: 0,   relY: 20, direction: 'S' },
      { id: 'OUT', relX: 0,   relY: -20, direction: 'N' },
    ],
    simParams: {
      displacement: { label: 'Displacement (cc/rev)', type: 'number', default: 18 },
      speed:        { label: 'Speed (rpm)', type: 'number', default: 1500 },
    },
  },
  {
    type: 'hyd_pump_variable',
    label: 'Variable Pump',
    tags: ['pump', 'variable', 'displacement', 'power', 'source', 'P'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'P',
    defaultValue: '',
    width: 40,
    height: 40,
    viewBox: '-24 -24 48 48',
    pins: [
      { id: 'IN',  relX: 0,  relY: 20, direction: 'S' },
      { id: 'OUT', relX: 0,  relY: -20, direction: 'N' },
    ],
    simParams: {
      maxDisplacement: { label: 'Max Displacement (cc/rev)', type: 'number', default: 28 },
      speed:           { label: 'Speed (rpm)', type: 'number', default: 1500 },
    },
  },
  {
    type: 'hyd_motor_fixed',
    label: 'Fixed Motor',
    tags: ['motor', 'fixed', 'displacement', 'actuator', 'M'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'M',
    defaultValue: '',
    width: 40,
    height: 40,
    viewBox: '-24 -24 48 48',
    pins: [
      { id: 'A', relX: 0,  relY: -20, direction: 'N' },
      { id: 'B', relX: 0,  relY: 20, direction: 'S' },
    ],
    simParams: {
      displacement: { label: 'Displacement (cc/rev)', type: 'number', default: 18 },
    },
  },
  {
    type: 'hyd_motor_variable',
    label: 'Variable Motor',
    tags: ['motor', 'variable', 'displacement', 'actuator', 'M'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'M',
    defaultValue: '',
    width: 40,
    height: 40,
    viewBox: '-24 -24 48 48',
    pins: [
      { id: 'A', relX: 0,  relY: -20, direction: 'N' },
      { id: 'B', relX: 0,  relY: 20, direction: 'S' },
    ],
    simParams: {
      maxDisplacement: { label: 'Max Displacement (cc/rev)', type: 'number', default: 28 },
    },
  },
  {
    type: 'hyd_reservoir',
    label: 'Reservoir',
    tags: ['tank', 'reservoir', 'sump', 'T'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'T',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -10, relY: -15, direction: 'N' },
      { id: 'B', relX:  10, relY: -15, direction: 'N' },
    ],
    simParams: {
      volume: { label: 'Volume (L)', type: 'number', default: 50 },
    },
  },
  {
    type: 'hyd_accumulator',
    label: 'Accumulator',
    tags: ['accumulator', 'bladder', 'piston', 'energy', 'ACC'],
    category: 'Power & Sources',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'ACC',
    defaultValue: '',
    width: 30,
    height: 50,
    viewBox: '-18 -28 36 56',
    pins: [
      { id: 'A', relX: 0, relY: 25, direction: 'S' },
    ],
    simParams: {
      precharge:  { label: 'Precharge (bar)', type: 'number', default: 100 },
      volume:     { label: 'Volume (L)', type: 'number', default: 10 },
    },
  },

  // ── Actuators ────────────────────────────────────────────────────────────────
  {
    type: 'hyd_cylinder_single',
    label: 'Single-Acting Cylinder',
    tags: ['cylinder', 'single', 'acting', 'linear', 'actuator', 'CYL'],
    category: 'Actuators',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'CYL',
    defaultValue: '',
    width: 60,
    height: 30,
    viewBox: '-32 -18 64 36',
    pins: [
      { id: 'A', relX: -28, relY: 0, direction: 'W' },
    ],
    simParams: {
      bore:   { label: 'Bore (mm)', type: 'number', default: 50 },
      stroke: { label: 'Stroke (mm)', type: 'number', default: 200 },
    },
  },
  {
    type: 'hyd_cylinder_double',
    label: 'Double-Acting Cylinder',
    tags: ['cylinder', 'double', 'acting', 'linear', 'actuator', 'CYL'],
    category: 'Actuators',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'CYL',
    defaultValue: '',
    width: 60,
    height: 30,
    viewBox: '-32 -18 64 36',
    pins: [
      { id: 'A', relX: -28, relY: 0, direction: 'W' },
      { id: 'B', relX:  28, relY: 0, direction: 'E' },
    ],
    simParams: {
      bore:      { label: 'Bore (mm)', type: 'number', default: 50 },
      rodDia:    { label: 'Rod Dia (mm)', type: 'number', default: 28 },
      stroke:    { label: 'Stroke (mm)', type: 'number', default: 200 },
    },
  },
  {
    type: 'hyd_cylinder_telescopic',
    label: 'Telescopic Cylinder',
    tags: ['cylinder', 'telescopic', 'multistage', 'CYL'],
    category: 'Actuators',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'CYL',
    defaultValue: '',
    width: 60,
    height: 30,
    viewBox: '-32 -18 64 36',
    pins: [
      { id: 'A', relX: -28, relY: 0, direction: 'W' },
    ],
    simParams: {
      stages: { label: 'Stages', type: 'number', default: 3 },
      stroke: { label: 'Total Stroke (mm)', type: 'number', default: 600 },
    },
  },
  {
    type: 'hyd_cylinder_steering',
    label: 'Steering Cylinder',
    tags: ['cylinder', 'steering', 'double', 'acting', 'through rod', 'double rod', 'ram', 'linear', 'actuator', 'CYL'],
    category: 'Actuators',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'CYL',
    defaultValue: '',
    width: 64,
    height: 38,
    viewBox: '-36 -22 72 44',
    pins: [
      { id: 'A', relX: -16, relY: 16, direction: 'S' },
      { id: 'B', relX:  16, relY: 16, direction: 'S' },
    ],
    simParams: {
      bore:   { label: 'Bore (mm)', type: 'number', default: 50 },
      rodDia: { label: 'Rod Dia (mm)', type: 'number', default: 28 },
      stroke: { label: 'Stroke (mm)', type: 'number', default: 200 },
    },
  },

  // ── Valves – Directional ──────────────────────────────────────────────────
  {
    type: 'hyd_dcv_4_2',
    label: '4/2 DCV',
    tags: ['valve', 'directional', 'control', 'DCV', '4/2', 'solenoid'],
    category: 'Valves – Directional',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'DCV',
    defaultValue: '',
    width: 130,
    height: 40,
    viewBox: '-66 -24 132 48',
    pins: [
      { id: 'P',  relX: -10, relY: 20, direction: 'S' },
      { id: 'T',  relX:  10, relY: 20, direction: 'S' },
      { id: 'A',  relX: -10, relY: -20, direction: 'N' },
      { id: 'B',  relX:  10, relY: -20, direction: 'N' },
    ],
    simParams: {
      actuation: { label: 'Actuation', type: 'select', options: ['solenoid', 'manual', 'pilot'], default: 'solenoid' },
    },
  },
  {
    type: 'hyd_dcv_4_3_open',
    label: '4/3 DCV (Open)',
    tags: ['valve', 'directional', 'control', 'DCV', '4/3', 'open center'],
    category: 'Valves – Directional',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'DCV',
    defaultValue: '',
    width: 160,
    height: 40,
    viewBox: '-80 -24 160 48',
    pins: [
      { id: 'P',  relX: -10, relY: 20, direction: 'S' },
      { id: 'T',  relX:  10, relY: 20, direction: 'S' },
      { id: 'A',  relX: -10, relY: -20, direction: 'N' },
      { id: 'B',  relX:  10, relY: -20, direction: 'N' },
    ],
    simParams: {
      centerPosition: { label: 'Center Position', type: 'select', options: ['open', 'closed', 'tandem', 'float'], default: 'open' },
      actuation: { label: 'Actuation', type: 'select', options: ['solenoid', 'manual', 'pilot'], default: 'solenoid' },
    },
  },
  {
    type: 'hyd_dcv_4_3_closed',
    label: '4/3 DCV (Closed)',
    tags: ['valve', 'directional', 'control', 'DCV', '4/3', 'closed center'],
    category: 'Valves – Directional',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'DCV',
    defaultValue: '',
    width: 160,
    height: 40,
    viewBox: '-80 -24 160 48',
    pins: [
      { id: 'P',  relX: -10, relY: 20, direction: 'S' },
      { id: 'T',  relX:  10, relY: 20, direction: 'S' },
      { id: 'A',  relX: -10, relY: -20, direction: 'N' },
      { id: 'B',  relX:  10, relY: -20, direction: 'N' },
    ],
    simParams: {
      actuation: { label: 'Actuation', type: 'select', options: ['solenoid', 'manual', 'pilot'], default: 'solenoid' },
    },
  },
  {
    type: 'hyd_dcv_2_2',
    label: '2/2 DCV',
    tags: ['valve', 'directional', '2/2', 'on-off', 'shutoff'],
    category: 'Valves – Directional',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'DCV',
    defaultValue: '',
    width: 130,
    height: 40,
    viewBox: '-66 -24 132 48',
    pins: [
      { id: 'P', relX: 0, relY:  20, direction: 'S' },
      { id: 'A', relX: 0, relY: -20, direction: 'N' },
    ],
    simParams: {
      normallyOpen: { label: 'Normal State', type: 'select', options: ['open', 'closed'], default: 'closed' },
    },
  },
  {
    type: 'hyd_dcv_3_2',
    label: '3/2 DCV',
    tags: ['valve', 'directional', '3/2'],
    category: 'Valves – Directional',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'DCV',
    defaultValue: '',
    width: 130,
    height: 40,
    viewBox: '-66 -24 132 48',
    pins: [
      { id: 'P', relX: -10, relY: 20, direction: 'S' },
      { id: 'T', relX:  10, relY: 20, direction: 'S' },
      { id: 'A', relX:   0, relY: -20, direction: 'N' },
    ],
    simParams: {
      normalPosition: { label: 'Normal Position', type: 'select', options: ['PT', 'PA'], default: 'PT' },
    },
  },

  // ── Valves – Pressure ─────────────────────────────────────────────────────
  {
    type: 'hyd_relief_valve',
    label: 'Relief Valve',
    tags: ['valve', 'relief', 'pressure', 'safety', 'RV'],
    category: 'Valves – Pressure',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'RV',
    defaultValue: '',
    width: 30,
    height: 40,
    viewBox: '-18 -22 36 44',
    pins: [
      { id: 'P', relX: 0, relY: -18, direction: 'N' },
      { id: 'T', relX: 0, relY:  18, direction: 'S' },
    ],
    simParams: {
      crackingPressure: { label: 'Cracking Pressure (bar)', type: 'number', default: 200 },
    },
  },
  {
    type: 'hyd_sequence_valve',
    label: 'Sequence Valve',
    tags: ['valve', 'sequence', 'pressure', 'SV'],
    category: 'Valves – Pressure',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'SV',
    defaultValue: '',
    width: 30,
    height: 40,
    viewBox: '-18 -22 36 44',
    pins: [
      { id: 'P', relX: 0, relY: -18, direction: 'N' },
      { id: 'A', relX: 0, relY:  18, direction: 'S' },
    ],
    simParams: {
      setPoint: { label: 'Set Pressure (bar)', type: 'number', default: 150 },
    },
  },
  {
    type: 'hyd_pressure_reducing',
    label: 'Pressure Reducing',
    tags: ['valve', 'pressure', 'reducing', 'PRV'],
    category: 'Valves – Pressure',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'PRV',
    defaultValue: '',
    width: 30,
    height: 40,
    viewBox: '-18 -22 36 44',
    pins: [
      { id: 'P', relX: 0, relY: -18, direction: 'N' },
      { id: 'A', relX: 0, relY:  18, direction: 'S' },
    ],
    simParams: {
      reducedPressure: { label: 'Reduced Pressure (bar)', type: 'number', default: 100 },
    },
  },
  {
    type: 'hyd_counterbalance',
    label: 'Counterbalance',
    tags: ['valve', 'counterbalance', 'load holding', 'CB'],
    category: 'Valves – Pressure',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'CB',
    defaultValue: '',
    width: 30,
    height: 40,
    viewBox: '-18 -22 36 44',
    pins: [
      { id: 'A', relX: 0, relY: -18, direction: 'N' },
      { id: 'B', relX: 0, relY:  18, direction: 'S' },
      { id: 'X', relX: 15, relY:  0, direction: 'E' },
    ],
    simParams: {
      setPoint: { label: 'Set Pressure (bar)', type: 'number', default: 160 },
    },
  },

  // ── Valves – Flow ─────────────────────────────────────────────────────────
  {
    type: 'hyd_check_valve',
    label: 'Check Valve',
    tags: ['valve', 'check', 'non-return', 'one-way', 'NRV'],
    category: 'Valves – Flow',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'NRV',
    defaultValue: '',
    width: 30,
    height: 30,
    viewBox: '-18 -18 36 36',
    pins: [
      { id: 'A', relX: -14, relY: 0, direction: 'W' },
      { id: 'B', relX:  14, relY: 0, direction: 'E' },
    ],
    simParams: {
      crackingPressure: { label: 'Cracking Pressure (bar)', type: 'number', default: 0.5 },
    },
  },
  {
    type: 'hyd_pilot_check',
    label: 'Pilot-Operated Check',
    tags: ['valve', 'check', 'pilot', 'operated', 'non-return', 'POCV'],
    category: 'Valves – Flow',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'POCV',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -22 44 44',
    pins: [
      { id: 'A', relX: -18, relY: 0, direction: 'W' },
      { id: 'B', relX:  18, relY: 0, direction: 'E' },
      { id: 'X', relX:   0, relY: 18, direction: 'S' },
    ],
    simParams: {
      pilotRatio: { label: 'Pilot Ratio', type: 'number', default: 3 },
    },
  },
  {
    type: 'hyd_flow_control',
    label: 'Flow Control',
    tags: ['valve', 'flow', 'control', 'throttle', 'needle', 'FC'],
    category: 'Valves – Flow',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'FC',
    defaultValue: '',
    width: 30,
    height: 30,
    viewBox: '-18 -18 36 36',
    pins: [
      { id: 'A', relX: -14, relY: 0, direction: 'W' },
      { id: 'B', relX:  14, relY: 0, direction: 'E' },
    ],
    simParams: {
      flowRate: { label: 'Flow Rate (L/min)', type: 'number', default: 10 },
    },
  },
  {
    type: 'hyd_flow_divider',
    label: 'Flow Divider',
    tags: ['valve', 'flow', 'divider', 'splitter', 'FD'],
    category: 'Valves – Flow',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'FD',
    defaultValue: '',
    width: 40,
    height: 40,
    viewBox: '-22 -24 44 48',
    pins: [
      { id: 'P', relX:   0, relY: -20, direction: 'N' },
      { id: 'A', relX: -15, relY:  20, direction: 'S' },
      { id: 'B', relX:  15, relY:  20, direction: 'S' },
    ],
    simParams: {
      ratio: { label: 'Split Ratio (%)', type: 'number', default: 50 },
    },
  },
  {
    type: 'hyd_shuttle_valve',
    label: 'Shuttle Valve',
    tags: ['valve', 'shuttle', 'OR', 'select', 'SHV'],
    category: 'Valves – Flow',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'SHV',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'A', relX: -18, relY: 0, direction: 'W' },
      { id: 'B', relX:  18, relY: 0, direction: 'E' },
      { id: 'Y', relX:   0, relY: -15, direction: 'N' },
    ],
    simParams: {},
  },

  // ── Conditioning ──────────────────────────────────────────────────────────
  {
    type: 'hyd_filter',
    label: 'Filter',
    tags: ['filter', 'strainer', 'conditioning', 'FIL'],
    category: 'Conditioning',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'FIL',
    defaultValue: '',
    width: 30,
    height: 40,
    viewBox: '-18 -22 36 44',
    pins: [
      { id: 'IN',  relX: 0, relY: -18, direction: 'N' },
      { id: 'OUT', relX: 0, relY:  18, direction: 'S' },
    ],
    simParams: {
      micron: { label: 'Filtration (µm)', type: 'number', default: 10 },
    },
  },
  {
    type: 'hyd_heat_exchanger',
    label: 'Heat Exchanger',
    tags: ['cooler', 'heat exchanger', 'conditioning', 'cooling', 'HE'],
    category: 'Conditioning',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'HE',
    defaultValue: '',
    width: 40,
    height: 30,
    viewBox: '-22 -18 44 36',
    pins: [
      { id: 'IN',  relX: -18, relY: 0, direction: 'W' },
      { id: 'OUT', relX:  18, relY: 0, direction: 'E' },
    ],
    simParams: {},
  },
  {
    type: 'hyd_pressure_gauge',
    label: 'Pressure Gauge',
    tags: ['gauge', 'pressure', 'instrument', 'PG'],
    category: 'Conditioning',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'PG',
    defaultValue: '',
    width: 30,
    height: 30,
    viewBox: '-18 -18 36 36',
    pins: [
      { id: 'A', relX: 0, relY: 14, direction: 'S' },
    ],
    simParams: {
      range: { label: 'Range (bar)', type: 'number', default: 250 },
    },
  },
  {
    type: 'hyd_flow_meter',
    label: 'Flow Meter',
    tags: ['meter', 'flow', 'instrument', 'FM'],
    category: 'Conditioning',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'FM',
    defaultValue: '',
    width: 30,
    height: 30,
    viewBox: '-18 -18 36 36',
    pins: [
      { id: 'IN',  relX: -14, relY: 0, direction: 'W' },
      { id: 'OUT', relX:  14, relY: 0, direction: 'E' },
    ],
    simParams: {
      range: { label: 'Range (L/min)', type: 'number', default: 100 },
    },
  },
  {
    type: 'hyd_temperature_gauge',
    label: 'Temperature Gauge',
    tags: ['gauge', 'temperature', 'instrument', 'TG'],
    category: 'Conditioning',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'TG',
    defaultValue: '',
    width: 30,
    height: 30,
    viewBox: '-18 -18 36 36',
    pins: [
      { id: 'A', relX: 0, relY: 14, direction: 'S' },
    ],
    simParams: {
      range: { label: 'Range (°C)', type: 'number', default: 100 },
    },
  },

  // ── Lines & Connectors ────────────────────────────────────────────────────
  {
    type: 'hyd_junction',
    label: 'T-Junction',
    tags: ['junction', 'tee', 'connection', 'node'],
    category: 'Lines & Connectors',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'J',
    defaultValue: '',
    width: 20,
    height: 20,
    viewBox: '-12 -12 24 24',
    pins: [
      { id: 'A', relX: -10, relY: 0, direction: 'W' },
      { id: 'B', relX:  10, relY: 0, direction: 'E' },
      { id: 'C', relX:   0, relY: 10, direction: 'S' },
    ],
    simParams: {},
  },
  {
    type: 'hyd_port',
    label: 'Port / End Cap',
    tags: ['port', 'end cap', 'plug', 'connection'],
    category: 'Lines & Connectors',
    schematicType: 'hydraulic',
    defaultDesignatorPrefix: 'PT',
    defaultValue: '',
    width: 20,
    height: 20,
    viewBox: '-12 -12 24 24',
    pins: [
      { id: 'A', relX: 0, relY: 0, direction: 'N' },
    ],
    simParams: {},
  },
]

export const HYDRAULIC_CATEGORIES = [
  'Power & Sources',
  'Actuators',
  'Valves – Directional',
  'Valves – Pressure',
  'Valves – Flow',
  'Conditioning',
  'Lines & Connectors',
]

export const ALL_HYDRAULIC_TYPES = new Set(HYDRAULIC_COMPONENTS.map(c => c.type))

export function getHydraulicDef(type) {
  return HYDRAULIC_COMPONENTS.find(c => c.type === type)
}
